### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'has_key'

### ISSUE THREAD

**Issue by MonikaPalaniappan** [jrtorres/conversation-simple-ui-python#3]
Hi , 

I have downloaded the conversation script and changed conversation id , name and workspace id then tried to run it. 
It got failed throwing the below error: 
Is it because of the python version I am using .To overcome with has_key how should i use the operator in ?
   
 **if(cont.has_key(INTERCEPT_FLAG_NAME)):**

Thanks and appreciate your help in advance !

Traceback (most recent call last):
  File "C:\python\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\python\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\python\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\python\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\python\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\python\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\python\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\python\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\python\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\python\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\sample_conversation\conversation-simple-ui-python\server.py", line 90, in Index_Post
    application_response = get_application_response(CONVERSATION_CONTEXT, question)
  File "C:\sample_conversation\conversation-simple-ui-python\orchestrator.py", line 45, in get_application_response
    application_response = enrich_application_response(response, question)
  File "C:\sample_conversation\conversation-simple-ui-python\orchestrator.py", line 37, in enrich_application_response
    if (intercept_requested(response)):
  File "C:\sample_conversation\conversation-simple-ui-python\orchestrator.py", line 29, in intercept_requested
    if(cont.has_key(INTERCEPT_FLAG_NAME)):
AttributeError: 'dict' object has no attribute 'has_key'

**Comment by MonikaPalaniappan** [comment]
This is working with **if(INTERCEPT_FLAG_NAME in cont):**. has_key doesn't support in 3.6 version.

Thanks,
Monika
